
version: '3.1'
services:
  nginx:
    build: ./nginx/
    container_name: "Nginx"
    depends_on:
      - php-fpm
    ports: 
      - "80:80"
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
  pgadmin:
    build: ./pgadmin/
    container_name: "pgAdmin"
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL:    "dev@example.com"
      PGADMIN_DEFAULT_PASSWORD: "pass4dev"
    ports:
      - "49153:80"
    volumes:
      - ./pgadmin/:/var/lib/pgadmin/
  php-fpm:
    build: ./php-fpm/
    container_name: "PHP-fpm"
    volumes:
      - ./nginx/html/:/usr/share/nginx/html/
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
  postgresql:
    build: ./postgresql/
    container_name: "PostgreSQL"
    environment:
      POSTGRES_PASSWORD: "pass4dev"
      POSTGRES_USER    : "dev"
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data/